### ISSUE TITLE
Unable to complete step 8 of sample process

### ISSUE THREAD

**Issue by noahheck** [microsoftgraph/php-connect-sample#1]
I keep getting a 500 Internal Server error (with a decidedly un-helpful message) after completing the process of granting permissions to the registered application:

```
ServerException in RequestException.php line 111:
Server error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `500 Internal Server Error` response:
{
"error": {
"code": "UnknownError",
"message": "{\"Status\":500,\"Message\":\"All the offeractions povided (truncated...)
```
I tried deleting the first application I registered and completing the steps again but continued to get the same result.

The `code` and `state` values appear to be appropriate values in the redirect URL (back to *localhost:8002/login*).

The `access_token` is set as expected on the session and provided to the `Graph` object in the `/email` route.

**Comment by caitlinrussell** [comment]
I've updated the scopes that the application asks for. It appears the "profile" scope is invalid for MSA accounts. This was also reported on the original REST sample [here](https://github.com/microsoftgraph/php-connect-rest-sample/issues/29).
