### ISSUE TITLE
At least one recipient isn't valid., A message c (truncated...)

### ISSUE THREAD

**Issue by chemo-baza** [microsoftgraph/php-connect-sample#10]
When I try to send any email after login always I receive this error:

"error": {
"code": "ErrorInvalidRecipients",
"message": "At least one recipient isn't valid., A message c (truncated...)

**Comment by fangj99** [comment]
Try the Graph Explorer to test first
https://developer.microsoft.com/en-us/graph/graph-explorer

I found the resolution for multiple recipients(test0@example.com, test1@example.com) when sendemail through msgraph php sdk, sample working code in the below:
```
{
  "message": {
    "subject": "Meet for lunch?",
    "body": {
      "contentType": "Text",
      "content": "The new cafeteria is open."
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "test0@example.com"
        }
      },
      {
        "emailAddress": {
          "address":"test1@example.com"
        }
      }
    ]
  }
}
```

**Comment by chemo-baza** [comment]
Hey! Awesome solution. Thank you so much!!!
