### ISSUE TITLE
../vendor/autoloader is missing

### ISSUE THREAD

**Issue by FredrikBrandt** [microsoftgraph/php-connect-sample#12]
Hi,
When running php artisan key:generate, this file is missing.
Also localhost doesn't have a port number (Wamp 3.1.3).

**Comment by Aminot1** [comment]
So you would need to run 
`composer install -v`
This will install all the framework (laravel) dependencies, along with MS Graph PHP SDK, they are found in composer.json file.

**Comment by MIchaelMainer** [comment]
@AminMkh I'm only slightly familiar with PHP so help me understand what the -v switch does? I don't see it described here: https://getcomposer.org/doc/03-cli.md#install-i

**Comment by noahheck** [comment]
@MIchaelMainer `-v` controls verbosity of output. From `composer -h`:

```
-v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by jasonjoh** [comment]
@FredrikBrandt we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-phpapp.
