### ISSUE TITLE
At least one recipient isn't valid.

### ISSUE THREAD

**Issue by saviorfromthenorth** [microsoftgraph/php-connect-sample#13]
```
ClientException in RequestException.php line 111:
Client error: `POST https://graph.microsoft.com/v1.0/me/sendMail` resulted in a `400 Bad Request` response:
{
"error": {
"code": "ErrorInvalidRecipients",
"message": "At least one recipient isn't valid., A message c (truncated...)
```

I get this error when I ran a fresh copy the sample.

**Comment by MIchaelMainer** [comment]
Can you share with us a copy of the request? Did you check the email address that was used in the sample to make sure that it is valid?

**Comment by jasonjoh** [comment]
@saviorfromthenorth we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-phpapp.
