### ISSUE TITLE
mcrypt_module_open() is deprecated

### ISSUE THREAD

**Issue by jkga** [microsoftgraph/php-connect-sample#3]
**ext/mcrypt** is **deprecated** in PHP **7.1.x**

source : [php.net](http://php.net/manual/en/migration71.deprecated.php)

**Comment by caitlinrussell** [comment]
This is a dependency called out two layers downstream from us. I've updated our OAuth2 dependency, but I don't believe it makes sense to override this behavior for the sake of the sample.

Thanks for finding this!

**Comment by jasonjoh** [comment]
@jkga we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-phpapp.
