### ISSUE TITLE
Uncaught exception for artisan

### ISSUE THREAD

**Issue by mckrti** [microsoftgraph/php-connect-sample#4]
I was directed to here form the php REST sample, and tried installing this.  However, when I get to `php artisan key:generate`, I get these errors:

Fatal error: Uncaught exception 'ReflectionException' with message 'Class App\Console\Kernel does not exist' in S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php:749
Stack trace:
#0 S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php(749): ReflectionClass->__construct('App\\Console\\Ker...')
#1 S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php(644): Illuminate\Container\Container->build('App\\Console\\Ker...', Array)
#2 S:\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(709): Illuminate\Container\Container->make('App\\Console\\Ker...', Array)
#3 S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php(231): Illuminate\Foundation\Application->make('App\\Console\\Ker...', Array)
#4 S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php(746): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 S:\htdocs\vendor\laravel\framework\src\ in S:\htdocs\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 749

**Comment by caitlinrussell** [comment]
Looks like you've run into multiple issues that are preventing you from connecting to Graph that we need to fix on our end. I will look into this shortly and get back to you on both this repo and the rest sample repo, then we can update SO from there.

**Comment by caitlinrussell** [comment]
Could you try running:
```php
composer dump-autoload
```
We can debug from there if that doesn't resolve your issue.
