### ISSUE TITLE
PHP 7.1 issue - function mcrypt_module_open() is deprecated

### ISSUE THREAD

**Issue by dan-silver** [microsoftgraph/php-connect-sample#5]
![image](https://user-images.githubusercontent.com/1266893/29047378-5f2a5622-7b80-11e7-8a2c-4526c4073610.png)

Downgrading to PHP 7.0 fixed the issue

**Comment by caitlinrussell** [comment]
See issue #3

**Comment by dan-silver** [comment]
Thanks.  It might be a good idea to leave this open as an FYI to developers until this is resolved.

**Comment by caitlinrussell** [comment]
Reopened #3
