### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by daniel503sv** [microsoftgraph/php-connect-sample#6]
is there a way top update a token, because all the data is saved in session vars, so yo cant access to the funcion refreshToken.

**Comment by caitlinrussell** [comment]
Yes, that is missing from the sample right now.

If you'd like to implement this, you can add this on line 76 of the [LoginController](https://github.com/microsoftgraph/php-connect-sample/blob/master/app/Http/Controllers/LoginController.php) to also save the refreshToken:

```php
$_SESSION['refresh_token'] = $accessToken->getRefreshToken();
```

You will then need to check if the access token is still valid, and if not, use the refresh token to get and store a new valid access token.

This sample uses The PHP League's Oauth2 client library, which has documentation on how to obtain the refresh token [here](https://github.com/thephpleague/oauth2-client#refreshing-a-token).
