### ISSUE TITLE
Function mcrypt_module_open() is deprecated

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/php-connect-sample#7]
I just followed the guide. Using PHP 7.1.11 on Windows. Visiting localhost:8000 generates the "Connect to Microsoft Graph" button but clicking that results in:

`ErrorException in AbstractMcryptMixer.php line 75:
Function mcrypt_module_open() is deprecated`

This is being generated by oauth.php.

**Comment by caitlinrussell** [comment]
Thanks for reporting this. You can track progress on this in issue #3
