### ISSUE TITLE
Issues link under Questions and comments links to different repository

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/php-connect-sample#8]
In README.MD, there's a line of text saying:

> You can send your questions and suggestions to us in the Issues section of this repository.

Issues links to: https://github.com/microsoftgraph/php-connect-rest-sample/issues

but I suspect it should be: https://github.com/microsoftgraph/php-connect-sample/issues

Regards,

Robin

**Comment by caitlinrussell** [comment]
Thanks for finding this! I have updated the link
