### ISSUE TITLE
Beta API returning ErrorAccessDenied

### ISSUE THREAD

**Issue by kjfdebruin** [microsoftgraph/php-connect-sample#9]
I am trying to access the beta API, specifically [user_findrooms](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_findrooms)

My application is registered, and has the required permissions. The user is logged in and redirected correctly. Calls to the v1 API work.

When I try to call the beta API like this:
```
$graph = new Graph();
$graph->setApiVersion('beta');
$graph->setAccessToken($_SESSION['access_token']);

$rooms = $graph->createRequest("get", "/me/findRooms")
                        ->setReturnType(Model\EmailAddress::class)
                        ->execute();
```

Then I get the following error:

> Client error: `GET https://graph.microsoft.com/beta/me/findRooms` resulted in a `403 Forbidden` response:
> {
> "error": {
> "code": "ErrorAccessDenied",
> "message": "Access is denied. Check credentials and try again.",
> (truncated...)

**Comment by kjfdebruin** [comment]
Looks like beta may not be the issue. I can successfully get the `/me` endpoint

Any idea which additional permissions are required to access `/me/findRooms`?

We have the following Graph permissions for our app:
**Delegated**: `User.ReadBasic.All` and `User.Read.All`
**Application permissions**: `Calendars.ReadWrite` and `User.Read.All`

**Comment by caitlinrussell** [comment]
Since this question is about the API and not the connect sample, could you ask your question on StackOverflow with the tag [microsoftgraph]? This will ensure that the right people see your question and you get an answer sooner!

**Comment by kjfdebruin** [comment]
Posted to StackOverflow [here](https://stackoverflow.com/questions/47449677/microsoft-graph-api-findrooms-erroraccessdenied)
